### ISSUE TITLE
Uppercase characters are vertically misaligned in the text line

### ISSUE THREAD

**Issue by myandrienko** [kosbarts/Commissioner#55]
For vertical alignment purposes it's convenient to have uppercase characters aligned to the middle of the text line. For that, descender metric should be equal to (ascender - cap height). This also a recommendation from Google Fonts: https://googlefonts.github.io/gf-guide/metrics.html#9-uppercases-should-be-centered-in-the-text-line

In Commissioner, the metrics are:

Ascent: 2034
Descent: -412
Cap height: 1426

So the gap above the top of uppercase characters is $2034 - 1426 = 608$ units, but the gap above is just 412 units.

I suggest to increase descent, decrease ascent, or both.

**Comment by myandrienko** [comment]
@kosbarts Thanks for the response!

If anyone else encounters this problem when using Commissioner as a web font, the following solution works in modern browsers except Safari:

```css
@font-face {
  font-family: "Commissioner";
  /* ... */
  ascent-override: 96.3%;
  descent-override: 25%;
}
```

This sets ascent to 1926 (0.963em given 2000 units-per-em of Commissioner), and descent to 500 (0.25em).
